1. Got the Test Exception
   Inside finally block